version: '3.8'

services:
   app:
    image: spring-boot-docker2.jar
    ports:
      -  8080:8080
    environment:
      SPRING-DATASOURCE-URL: jdbc:mysql://localhost:3306/grocerycrud
      SPRING-DATASOURCE-USERNAME: root
      SPRING-DATASOURCE-PASSWORD: root
    depends_on:
    - db
    
   db :
      image : mysql:8.0.27
      environment:
        DATABASE_HOST: docker-mysql
        DATABASE_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: grocerycrud
        MYSQL-USER: root
        MYSQL-PASSWORD: root	
   
   
    
    
    